apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-ssh-public
spec:
  rules:
    - name: check-ssh-public
      assert:
        all:
          # Check root module security groups
          - check:
              "(length(planned_values.root_module.resources[?type == 'aws_security_group'].values.ingress[][] | [?from_port <= `22` && to_port >= `22` && contains(cidr_blocks, '0.0.0.0/0')] || `[]`))": 0
          # Check child module security groups
          - check:
              "(length(planned_values.root_module.child_modules[].resources[?type == 'aws_security_group'].values.ingress[][] | [?from_port <= `22` && to_port >= `22` && contains(cidr_blocks, '0.0.0.0/0')] || `[]`))": 0
          # Check root module security group rules
          - check:
              "(length(planned_values.root_module.resources[?type == 'aws_security_group_rule'].values | [?type == 'ingress' && from_port <= `22` && to_port >= `22` && contains(cidr_blocks, '0.0.0.0/0')] || `[]`))": 0
          # Check child module security group rules
          - check:
              "(length(planned_values.root_module.child_modules[].resources[?type == 'aws_security_group_rule'].values | [?type == 'ingress' && from_port <= `22` && to_port >= `22` && contains(cidr_blocks, '0.0.0.0/0')] || `[]`))": 0
