name: Infrastructure CI (Terraform Security)
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - 'policies/tf-policies/**'

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Generate Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Convert Plan to JSON
      run: terraform show -json tfplan > plan.json
      working-directory: ./terraform

    - name: Install Kyverno JSON CLI
      uses: kyverno/action-install-kyverno-json@v0.0.1
      with:
        release: 'v0.0.3'

    - name: Scan Terraform Plan with Kyverno JSON
      run: kyverno-json scan --payload ./terraform/plan.json --policy ./policies/tf-policies/
