apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-secret-regcred
  annotations:
    policies.kyverno.io/title: Clone Secret regcred
    policies.kyverno.io/description: >-
      This policy listens for the creation of a new Namespace. 
      Immediately upon creation, it automatically clones the `regcred` Secret
      from the `default` Namespace into the newly created Namespace.
spec:
  rules:
    - name: clone-secret
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
                - default
      generate:
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: regcred
        namespace: "{{request.object.metadata.name}}"
        clone:
          namespace: default
          name: regcred
