apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-image-signatures
spec:
  validationActions: [Deny]
  failurePolicy: Fail
  webhookConfiguration:
    timeoutSeconds: 30

  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  matchImageReferences:
    - glob: "registry.awsfcaj.com/wineapp/*"
  credentials:
    secrets:
      - registry-secret
  attestors:
    - name: cosign
      cosign:
        keyless:
          identities:
            - issuer: "https://token.actions.githubusercontent.com"
              subjectRegExp: "https://github.com/tranvix0910/.*/.github/workflows/.*"
        ctlog:
          url: "https://rekor.sigstore.dev"
  validationConfigurations:
    mutateDigest: true
    required: true
    verifyDigest: true
  validations:
    - expression: >-
        images.containers.map(image, verifyImageSignatures(image, [attestors.cosign])).all(e, e > 0)
      message: >-
        All images from registry.awsfcaj.com/wineapp/* must be signed by GitHub Actions CI/CD.
        Unsigned or tampered images are strictly forbidden.
